### ISSUE TITLE
Issues with ETS2 mudflaps

### ISSUE THREAD

**Issue by WerewolfCustoms** [WerewolfCustoms/ModsStudio2IssueBoard#102]
Oli has had similar issues with ETS2. His log is below.

He fixed the issue by selecting only selecting SCS Box Trailer; rather than selecting all 4 SCS trailers. Selecting more than one causes a crash according to Oli.

> -----------------------------------------------------------------------------
> Date : 26/03/2021 14:54:05
> 
> System.IO.DirectoryNotFoundException
> Message : Could not find a part of the path 'C:\Users\Olivier\Desktop\Games\Modding tools\skins ets2\Data\ModProjects\ETS2\Templates\TrailerMudflap\scs_trailer\automat\94\94c4c63ab2c4a6e6.mat'.
> StackTrace :    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
>    at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
>    at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
>    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
>    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
>    at System.IO.File.ReadAllText(String path)
>    at ModsStudio2Library.Logic.ScsMod.Actions.ModifyPmdMaterials.ProcessPmdFile(Template template, String filePath) in D:\Sources\ModsStudio2\ModsStudio2Library\Logic\ScsMod\Actions\ModifyPmdMaterials.cs:line 34
>    at ModsStudio2Library.Logic.ScsMod.Actions.ModifyPmdMaterials.Execute(Template template) in D:\Sources\ModsStudio2\ModsStudio2Library\Logic\ScsMod\Actions\ModifyPmdMaterials.cs:line 73
>    at ModsStudio2Library.Logic.Actions.ProcessArrayValues.Execute(Template template) in D:\Sources\ModsStudio2\ModsStudio2Library\Logic\Actions\ProcessArrayValues.cs:line 41
>    at ModsStudio2Library.Models.Template.Build(VariableList enviroment) in D:\Sources\ModsStudio2\ModsStudio2Library\Models\Template.cs:line 26
>    at ModsStudio2Library.Models.ScsMod.ScsProject.Build(VariableList enviromentVariables) in D:\Sources\ModsStudio2\ModsStudio2Library\Models\ScsMod\ScsProject.cs:line 30
>    at ModsStudio2Core.Logic.Build.BuildProjectFile(String inputPath, String outputPath) in D:\Sources\ModsStudio2\ModsStudio2Core\Logic\Build.cs:line 70
>    at ModsStudio2Core.CLI.BuildOptionsHandler.ParseOptions(BuildOptions opts) in D:\Sources\ModsStudio2\ModsStudio2Core\CLI\BuildOptions.cs:line 49
>    at ModsStudio2Core.Program.<>c.<ProcessInput>b__3_2(BuildOptions opts) in D:\Sources\ModsStudio2\ModsStudio2Core\Program.cs:line 104
>    at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
>    at ModsStudio2Core.Program.ProcessInput(String[] args) in D:\Sources\ModsStudio2\ModsStudio2Core\Program.cs:line 96
>    at ModsStudio2Core.Program.Main(String[] args) in D:\Sources\ModsStudio2\ModsStudio2Core\Program.cs:line 79
>

_Originally posted by @pete-agreatguy in https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/issues/97#issuecomment-808243365_

**Comment by WerewolfCustoms** [comment]
I've tested this today, and it works as intended. This _might_ have been fixed by recent bugfixes;
