### ISSUE TITLE
ATS - Project Template: RearTrailerMudflaps Error Issues Exporting

### ISSUE THREAD

**Issue by Mike7O** [WerewolfCustoms/ModsStudio2IssueBoard#97]
### export failures:

> **-----------------------------------------------------------------------------**
System.IO.FileNotFoundException
**Message : Could not find file 'D:\Mods Studio 2 v.2021.01\Temp\ModBuild\vehicle\trailer_owned\upgrade\r_mudflap\ms2\atsmud\scs.box.pmd'.**
StackTrace :    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode)
   at ModsStudio2Library.Files.ScsMod.Pmd..ctor(String path) in D:\Sources\ModsStudio2\ModsStudio2Library\Files\ScsMod\Pmd.cs:line 37
   at ModsStudio2Library.Logic.ScsMod.Actions.ModifyPmdMaterials.ProcessPmdFile(Template template, String filePath) in D:\Sources\ModsStudio2\ModsStudio2Library\Logic\ScsMod\Actions\ModifyPmdMaterials.cs:line 36
   at ModsStudio2Library.Logic.ScsMod.Actions.ModifyPmdMaterials.Execute(Template template) in D:\Sources\ModsStudio2\ModsStudio2Library\Logic\ScsMod\Actions\ModifyPmdMaterials.cs:line 78
   at ModsStudio2Library.Models.Template.Build(VariableList enviroment) in D:\Sources\ModsStudio2\ModsStudio2Library\Models\Template.cs:line 26
   at ModsStudio2Library.Models.ScsMod.ScsProject.Build(VariableList enviromentVariables) in D:\Sources\ModsStudio2\ModsStudio2Library\Models\ScsMod\ScsProject.cs:line 30
   at ModsStudio2Core.Logic.Build.BuildProjectFile(String inputPath, String outputPath) in D:\Sources\ModsStudio2\ModsStudio2Core\Logic\Build.cs:line 70
   at ModsStudio2Core.CLI.BuildOptionsHandler.ParseOptions(BuildOptions opts) in D:\Sources\ModsStudio2\ModsStudio2Core\CLI\BuildOptions.cs:line 47
   at ModsStudio2Core.Program.<>c.<ProcessInput>b__3_2(BuildOptions opts) in D:\Sources\ModsStudio2\ModsStudio2Core\Program.cs:line 105
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at ModsStudio2Core.Program.ProcessInput(String[] args) in D:\Sources\ModsStudio2\ModsStudio2Core\Program.cs:line 96
   at ModsStudio2Core.Program.Main(String[] args) in D:\Sources\ModsStudio2\ModsStudio2Core\Program.cs:line 77
**-----------------------------------------------------------------------------**
In the  D:\Mods Studio 2 v.2021.01\Temp\ModBuild\vehicle\trailer_owned\upgrade\r_mudflap\ms2\atsmud\
there is a **mudflap.pmd**.

**ORIGINAL:** 
```
<Action xsi:type="CopyFile">
      <Paths>
        <CopyPair>
          <From>scs_trailer\automat\</From>
          <To>vehicle\trailer_owned\upgrade\r_mudflap\ms2\{{InternalName}}\</To>
        </CopyPair>
        <CopyPair>
          <From>scs_trailer\{{Trailer.MudflapModel}}.pmd</From>
          <To>vehicle\trailer_owned\upgrade\r_mudflap\ms2\{{InternalName}}\mudflap.pmd</To>
        </CopyPair>
        <CopyPair>
          <From>scs_trailer\{{Trailer.MudflapModel}}.pmg</From>
          <To>vehicle\trailer_owned\upgrade\r_mudflap\ms2\{{InternalName}}\mudflap.pmg</To>
        </CopyPair>
        <CopyPair>
          <From>scs_trailer\skin.tobj</From>
          <To>vehicle\trailer_owned\upgrade\r_mudflap\ms2\{{InternalName}}\skin.tobj</To>
        </CopyPair>
        <CopyPair>
          <From>scs_trailer\{{Trailer.MudflapModel}}.sii</From>
          <To>def\vehicle\trailer_owned\{{Trailer}}\accessory\r_mudflap\{{InternalName}}.sii</To>
        </CopyPair>
      </Paths>
    </Action>
    <Action xsi:type="ModifyPmdMaterials">
      <FilePath>vehicle\trailer_owned\upgrade\r_mudflap\ms2\{{InternalName}}\{{Trailer}}.pmd</FilePath>
      <MaterialsPath>scs_trailer\</MaterialsPath>
      <ReplaceData>
        <SearchFor>/vehicle/trailer/upgrade/mudflap/ms2/</SearchFor>
        <ReplaceWith>/vehicle/trailer_owned/upgrade/r_mudflap/ms2/{{InternalName}}/</ReplaceWith>
      </ReplaceData>
    </Action>
```

*a few testing and the issue caused by this line:*
```
**<Action xsi:type="ModifyPmdMaterials">
      <FilePath>vehicle\trailer_owned\upgrade\r_mudflap\ms2\{{InternalName}}\{{Trailer}}.pmd</FilePath>**
```

*changed the* **{{Trailer}}.pmd**  *to* **mudflap.pmd** *and it exported without issues*. 
**_________________________________________________________________________________________________________________**
So what is the correct way..should it modify the pmd to  **{{Trailer}}.pmd** 
(which seems NOT be working properly) or keep the filename to **mudflap.pmd**

**Comment by Mike7O** [comment]
and while browsing old posts on the channel I found something .... related to this (perhaps) https://discord.com/channels/611134812471820348/611170373773295616/807718372229251193

the added .zip by MDModding isn't the same as in the MS2release..but tried using the info given below the zip to the existing one in MS2...
and as usual not knowing what I'm doing - NOT a happy result .....

**Comment by samueldevos** [comment]
I too had the same issue, Here is a screenshot of my error.

![error](https://user-images.githubusercontent.com/80008666/109877275-d0564d00-7c40-11eb-93fa-3eb17619c5f2.png)

I tried Mike70's fix, and it exported the mod no problem. Tested with 1.40 beta and it worked

**Comment by samueldevos** [comment]
After further investigations, by using the fix Mike70 suggested, I noticed that for the SCS_Box trailer "ch_53_4a.scs.box.chassis" and "ch_53_4s.scs.box.chassis", it applies the box "simple" (seen on 1-3 axle chassis).

**Comment by pete-agreatguy** [comment]
Oli has had similar issues with ETS2. His log is below.

> 
[oli_ets2_log.txt](https://github.com/WerewolfCustoms/ModsStudio2IssueBoard/files/6212256/oli_ets2_log.txt)
